# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build for Android

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Get Latest Release
        id: release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          owner: turtlepaw
          repo: BlueskyRedirect
          token: ${{ secrets.GITHUB_TOKEN }}
          excludes: "prerelease, draft"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ${{ github.workspace }}/app/build
            ${{ github.workspace }}/shared/build
          key: ${{ runner.os }}-gradle-android-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-android-

      - name: Build app
        run: |
          ./gradlew :app:packageRelease
          ./gradlew --stop

      - name: Upload app logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: app_logs
          path: ${{ github.workspace }}/app/build/outputs/logs/

      - name: Check app APKs exists
        run: ls -laR ${{ github.workspace }}/app/build/outputs/apk/

      - name: Sign APK
        id: sign_apk
        uses: zacharee/zipalign-sign-android-release@2.0.0
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_KEY_PWD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PWD }}
        env:
          BUILD_TOOLS_VERSION: "35.0.0"

      - name: Upload APK
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Signed APK
          path: ${{ steps.sign_apk.outputs.signedReleaseFile }}

      - name: Add APK to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.workspace }}/${{ steps.sign_apk.outputs.signedReleaseFile }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: false
          omitBodyDuringUpdate: true
          tag: ${{ steps.release.outputs.release }}

