name: Tangle

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tangle:
    runs-on: ubuntu-latest
    steps:
      - uses: gwennlbh/to-tangled@v0.3
        with:
          repo: did:plc:u2grpouz5553mrn4x772pyfa/bluesky_redirect
          ssh-key: ${{ secrets.TANGLED_KEY }}